import "./Malaysia.css";

function Malaysia() {
  return (
    <div className="parent">
      {/* <p className="first">
        1 LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM
        IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM
        IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM
        IPSUM LOREM IPSUM LOREM IPSUM
      </p>
      <p className="second">
        2 QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS
        QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM
        PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS
        QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM
        PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS
        QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM
        PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS
        QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM
        PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS
      </p>
      <p className="third">
        3 LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM
        IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM
        IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM IPSUM LOREM
        IPSUM LOREM IPSUM LOREM IPSUM
      </p>
      <p className="fourth">
        4 QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS
        QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM
        PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS
        QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM PHYSICS QUANTAM
      </p> */}

      <div className="main">CSS Box-Model Property</div>
      <div id="model">
        <p>Box</p>
        <p>
          <i>Model</i>
        </p>
      </div>
    </div>
  );
}

export default Malaysia;
